### ISSUE TITLE
Redirecting Traffic

### ISSUE THREAD

**Issue by ModernAesthetics** [alandau/arpspoof#1]
How would one redirect traffic with this?

**Comment by alandau** [comment]
Look in the README file, it explains it. Specifically the TL;DR section shows an example.
```
arpspoof.exe 192.168.1.10
```
This will inject the local machine between 192.168.1.10 and the default gateway.

Let me know where things are not clear so I can update the doc!

**Comment by alandau** [comment]
Closing this issue. Please reopen if you need more help.

**Comment by cupzyy** [comment]
@alandau I am running `arpspoof 192.168.10.1` but I still have this issue, it does get the incoming traffic but it doesn't redirect the traffic to the router
