### ISSUE TITLE
I can't run because of file

### ISSUE THREAD

**Issue by r-clues** [alandau/arpspoof#11]
If I turn on exe file, it says "wpcap.dll" does not exist.
how can I get wpcap.dll?

**Comment by alandau** [comment]
wpcap.dll is part of WinPcap and Npcap. The former is deprecated so you should use the latter. It is also installed by Wireshark, and I recommend you to just install it: https://www.wireshark.org/

I updated arpspoof to better support Npcap, so after installing Wireshark, please try with version v0.2 of arpspoof: https://github.com/alandau/arpspoof/releases/tag/v0.2

**Comment by r-clues** [comment]
Thank you
