### ISSUE TITLE
arpspoof

### ISSUE THREAD

**Issue by buddy228** [alandau/arpspoof#14]
KALI-LINUX :please help..after using #arpspoof -i eth0 -t (terget ip) (gateway) #arpspoof -i eth0 -t (gateway) (terget ip) then terget machin cant access internet and then i do ip forword using this command #echo 1 > /proc/sys/net/ipv4/ip_forward....but same problem terget machin cant access internet..BUT SAME PROCESS apply on ubuntu (after install all the tool in ubuntu) its work but in kali linux its not working........please help what should i do??

**Comment by alandau** [comment]
This project is the Windows `arpspoof` tool, which is different from the one included in common Linux distros, even though it's also called `arpspoof`. You can try your luck on the other tool's mailing list.
I don't know why it works on Ubuntu and doesn't on Kali. I'd try capturing packets with `tcpdump` to see what's being sent.
