### ISSUE TITLE
Can't resolve victim IP, is it up?

### ISSUE THREAD

**Issue by ryaquaza** [alandau/arpspoof#15]
Hello, I try to run command "arpspoof.exe 192.16.1.15" and get the message "Resolving victim and target....  Can't resolve victim IP, is it up?" The computer I am using has address 11, the other 2 machines have addresses 15, 16 respectively. Do you have any suggestions? Thank you very much.

**Comment by ryaquaza** [comment]
Hello.
![Capture](https://user-images.githubusercontent.com/51154728/120581684-6888eb80-c455-11eb-87db-81eed03abc36.PNG)
 I faced this problem today, do you have any solution for it? Thank you very much.

**Comment by alandau** [comment]
By default the target is the default gateway. In this case, the default gateway is not set (`--list` shows 0.0.0.0). You need to either set a default gateway on your NIC (and then `arpspoof` will redirect messages between 192.168.0.11 and the default gateway to go through the local computer), or run `arpspoof` with the target as the second argument (e.g., `arpspoof 192.168.0.11 192.168.0.100`).

**Comment by ryaquaza** [comment]
Thanks for your answer, it helped me. But I still don't understand why I run "arpspoof 192.168.0.11 192.168.0.22" it works fine, but when I use "arpspoof 192.168.0.11 or arpspoof 192.168.0.22"it gives error: Can't resolve victim IP, is it up?

**Comment by ryaquaza** [comment]
I did it, thank you.
