### ISSUE TITLE
Is it possible to run without installing Wireshark?

### ISSUE THREAD

**Issue by ryaquaza** [alandau/arpspoof#16]
Hello, I want to ask is there a way to run arpspoof without having to install Wirehark? For example just add .lib or dll file to generated .exe folder?

**Comment by alandau** [comment]
A kernel driver (WinPcap or Npcap) has to be installed for arpspoof to run. The library arpspoof uses to talk to the driver is already statically linked into the .exe so no further DLLs are required.

Wireshark is not required per se, but it's a convenient way to install the driver. However, you can install the driver directly without Wireshark: https://nmap.org/npcap/#download.

**Comment by ryaquaza** [comment]
Many thanks for your answer. I want to ask that instead of installing the kernel driver, can I directly add WinPcap include, WinPcap library(I found it in NpcapSDK) to the source code to compile or not?

**Comment by alandau** [comment]
No, it's not _instead_, it's _in addition_. The pcap library from the SDK is already included in the .exe, but you also need the driver, which is separate and has to be installed.

**Comment by ryaquaza** [comment]
Thanks for your help.
