### ISSUE TITLE
Ability to directly pass in MAC address

### ISSUE THREAD

**Issue by Kenji776** [alandau/arpspoof#19]
Hello,

I am attempting to spoof a device that does not want to resolve that I know is up (my own phone). I am guessing mobile phones don't reply the way the arpspoof requires (it doesn't respond to pings at all). Would it be possible to add a feature to just hard code in a MAC that we know exists?

**Comment by alandau** [comment]
While adding this feature is surely possible, I don't think it'll help in this case. `arpspoof` needs to send ARP messages to both the victim and the target (phone and router) so if the phone doesn't process ARP messages (e.g., it's in a deep sleep state), specifying the MAC won't help. BTW, the phone doesn't have to reply to pings for `arpspoof` to work, but it does have to process ARP messages.
What I usually do is I make sure the phone is unlocked with the screen on, and that in Wi-Fi settings, the setting to switch from Wi-Fi to mobile after a certain time is turned off.
Hope this helps.

**Comment by Kenji776** [comment]
Thanks for the reply. For what its worth I tried using Cain and Able and manually modified the hosts list for arp route poisoning and that did work even though the device was not responding to pings. Just food for thought.
