### ISSUE TITLE
When bridged connection 

### ISSUE THREAD

**Issue by diegodp-zz** [alandau/arpspoof#2]
i trying to coonect my notebook to my game pc thought arpspoof, but when connected, i can't acess steam.. Google works and some other website work fine, but steam and some others not (github don't work too).

So i am trying to bridge the connection betwen my Game pc and my notebook too see if steam works , but i get this error in arpspoof:

"arpspoof tells that "Can´t find interface (explicity specified or matching victim IP)" <--even that IP is correct 0

**Comment by acvilonre** [comment]
Im struggling with the same issue.

**Comment by alandau** [comment]
I'm not sure I understand what you're trying to do with steam and the notebook, but the arpspoof error is most likely due to WinPcap not returning a list of interfaces.

Do you have WinPcap installed? Or Wireshark, which installs WinPcap by default.
What is the output of `arpspoof --list`?

**Comment by acvilonre** [comment]
Well I do not know about the fellow above but my issue is that I have two computer directly next to eachother, One of which has a wifi adapter and I bridge the connect to my gaming pc. So when I go to run the arpspoof.exe 192.168.X.XXX I get a return of "Can´t find interface (explicity specified or matching victim IP)". I do have WinCap 4.1.3 installed.

**Comment by diegodp-zz** [comment]
The output from arpspoof --list is none.. 

Yes i have wireshark, the problem only happens when bridged connection. 

When not bridged and the 2 computers are in the same lan, i can connect with arpspoof, but as i have said, steam and others website like github don't connect then. 

Google and some other websites work fine, which is strange .. Some websites connect and some do not. Anyway, I needed to run a steam game. So I'm trying on bridge mode, to see if it connects.

**Comment by alandau** [comment]
@wasdasf: Is the `--list` output empty for you as well?
@diegodp: An empty `--list` means WinPcap can't capture on any interface which is up. Usually it means all interfaces are disabled (or have the cable disconnected, etc), but maybe WinPcap doesn't work with the software bridge? I'm not sure.

So the `Can´t find interface` error is probably due to the WinPcap limitation (unless I'm doing something fishy when matching pcap interfaces to Windows').

When not bridging, a .pcap file showing a successful connection to google, and another one showing the non-working websites might help debug this.

**Comment by acvilonre** [comment]
Yeah I am getting a empty output for --list.

**Comment by alandau** [comment]
I'm assuming WinPcap doesn't support capturing on bridged connections. In this case, there's nothing I can do. You guys might want to try a different WinPcap-compatible driver (such as [Win10Pcap](http://www.win10pcap.org/) or [Npcap](https://nmap.org/npcap/)). I haven't tested these, however.

If you capture and upload a .pcap file for when you run without the bridge showing both the working and non-working sites, I can take a look, perhaps I'll spot something.

**Comment by alandau** [comment]
Please reopen if you still have issues
