### ISSUE TITLE
Accept multiple targets

### ISSUE THREAD

**Issue by Apoptosys** [alandau/arpspoof#23]
Sorry to open a new issue for this, but there's no discussion tab. Do you intend to make a version which allows for multiple targets to be monitored at the same time? 
If not, can you provide some hints as to how the code should be modified? Thank you!

**Comment by alandau** [comment]
Such a version is not something I planned on doing.
You can achieve it by running multiple instances of arpspoof, each with a different victim/target.
Or, if you wish to do it in code, loop over all victims/targets whenever you see the code doing something with the (single) victim/target. The latter approach has some edge cases that need to be thought through, e.g. what if the victims are reachable through different interfaces, is there a single target for all victims or one for each, etc.
