### ISSUE TITLE
PacketSendPacket failed (error 31)

### ISSUE THREAD

**Issue by lucadomene** [alandau/arpspoof#24]
I am experiencing this quite frustrating issue, which might be related to a very slow internet browsing on the victim's device.
After issuing the command with the victim's IP, the following message comes up (at least 100 times, and it keeps going):
`Error forwarding packet: send error: PacketSendPacket failed: A device attached to the system is not functioning.  (31)`

I have tried several possible fixes: reinstalling Wireshark and Npcap, downloading Npcap from its original website, tried disabling my antivirus and running CMD and Powershell in Administrative Mode.

The ARP Poisoning seems to be working fine, I am able to intercept packages and data, but I am not sure if that error is supposed to come up on my machine. I am using Windows 11 on build 22000.527.

**Comment by alandau** [comment]
Interesting, I haven't seen anything like this and a quick google didn't find anything directly related. Perhaps, an incompatibility of npcap with Windows 11? I'm using npcap 1.31 on Windows 10 and it works for me. Perhaps try using this version on Windows 11 and see if it helps?
Is the CPU on which arpspoof runs busy 100%? If so, perhaps npcap can't intercept/send packets fast enough for a regular browsing session.
Can you try running arpspoof on a different network interface? E.g. use Ethernet if you tried Wi-Fi or vice versa.

**Comment by alexanderbeloiu** [comment]
Updating to the latest npcap solved the issue for me.
