### ISSUE TITLE
Is it possible to not forward packets, and block the victims internet access?

### ISSUE THREAD

**Issue by alexanderbeloiu** [alandau/arpspoof#27]
Is it possible to not forward packets, and block the victims internet access? I have tried the --oneway argument, and it doesn't seem to do this.

**Comment by alandau** [comment]
Not right now. But it should be fairly easy to add an option that just does the spoofing without forwarding traffic. Happy to accept a PR.
Note that if you only want to block traffic, it's likely easier to do it at the firewall.
