### ISSUE TITLE
How can I use it with Mitmproxy?

### ISSUE THREAD

**Issue by Ikaleio** [alandau/arpspoof#31]
How can I redirect https transmission to localhost:8080?

**Comment by alandau** [comment]
You can't change the port, since arpspoof works below the TCP layer.
You can redirect the IP using `arpspoof.exe 192.168.1.10` (as stated in the README), where 192.168.1.10 is the IP of the machine sending traffic.

**Comment by Ikaleio** [comment]
> You can't change the port, since arpspoof works below the TCP layer. You can redirect the IP using `arpspoof.exe 192.168.1.10` (as stated in the README), where 192.168.1.10 is the IP of the machine sending traffic.

So, how can I capture the flow with Mitmproxy? Just simply set the proxy port to 80/443?

**Comment by alandau** [comment]
I don't know, I haven't used mitmproxy. I guess at some point you need to redirect the client's messages destined via the router to the internet to go to the mitmproxy box (localhost). That's what `arpspoof <client-ip>` does.
