### ISSUE TITLE
can't run this

### ISSUE THREAD

**Issue by Traviboi** [alandau/arpspoof#32]
when running the EXE it closes with error code 1

**Comment by alandau** [comment]
Did you install npcap as per the README?

**Comment by crjase** [comment]
> Did you install npcap as per the README?
. 
maybe make a warning message pop up if there's a missing dependency.

**Comment by alandau** [comment]
It's possible, but is a hassle. Given this tool already requires networking knowledge, I'm assuming a user would be able to read the README and figure out npcap is needed.
