### ISSUE TITLE
Can't resolve victim IP, is it up?

### ISSUE THREAD

**Issue by RekhzzOnly** [alandau/arpspoof#33]
Hello can someone teach me how to fix it??

![image](https://github.com/alandau/arpspoof/assets/167624822/65bbbcf9-ff1d-47fb-8355-c1c9332ceff1)

**Comment by alandau** [comment]
You're trying to spoof your own address, while you should specify an IP of a different host on your network (e.g. 198.18.0.2). Also, interface 1 looks like a VPN and is unlikely to use ARP.
