### ISSUE TITLE
Can´t find interface (explicitly specified or matching victim IP)

### ISSUE THREAD

**Issue by simonmy** [alandau/arpspoof#5]
I am trying to get the packets from my main pc for a pubg radar.
laptop+pc are connected by the same wlan(tried it with lan didnt change anything).
my command on the laptop(win10) is arpspoof.exe 192.168.178.50(gaming pc-ip) tried it with -i 1 and  -t(not necessary on win).

**Comment by alandau** [comment]
1. Did you install WinPcap?
2. What is the output of `arpspoof --list`?

**Comment by simonmy** [comment]
1. Yes I installed winpcap(this https://www.winpcap.org/install/) 
2. it just gives me an empty line

**Comment by alandau** [comment]
An empty `--list` means that there are no interfaces in common between what Windows reports as the available interfaces and what WinPcap reports as interfaces it can capture on.

1. Can Wireshark capture on the WiFi interface?
2. If yes, can you post 2 screenshots in Wireshark?  1 - Capture->Options. 2 - Capture->Options->Manage Interfaces

**Comment by simonmy** [comment]
Thanks!
Just deinstalling winpcap and installing it with wireshark+ starting capture->options fixed my problem!
