### ISSUE TITLE
Recent issue reports

### ISSUE THREAD

**Issue by garyjohnson21** [alandau/arpspoof#6]
Hello,

Sorry to leave this as an "issue" but Github doesn't have private messaging feature.  I just wanted to let you know why you've suddenly started getting issue reports from people who don't seem to know what they're doing nor what this utility actually does.

There is a "radar" program (3rd party cheat) for the game PlayerUnknown's Battlegrounds (PUBG) that a lot of cheaters have picked up on recently.  One of the methods to set it up without being detected by the game as a cheater is to run arpspoof on a second PC to intercept traffic from the gaming PC.  The "radar" program uses winpcap to read the unencrypted game traffic and show enemy locations on the radar.  When searching for a Windows arpspoof, yours is the first result on Google.  It's also the one that is commonly linked by the radar developers.

Thank you for this project.  I don't think any of the open issue reports are actually valid, just cheaters who can't figure out how to set it up.

**Comment by alandau** [comment]
I was actually wondering why the influx of issues and whether this is the reason or the outcome of the high Google rank.
Thank you for your comment, I really appreciate it!
