### ISSUE TITLE
Can't run this

### ISSUE THREAD

**Issue by ChocoTonic** [alandau/arpspoof#7]
---------------------------
arpspoof.exe - System Error
---------------------------
The program can't start because wpcap.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

**Comment by alandau** [comment]
Did you install WinPcap/Wireshark?

**Comment by ChocoTonic** [comment]
yes
![image](https://user-images.githubusercontent.com/41702116/44850677-d5228c00-ac12-11e8-8226-040bc58e6ee6.png)
i get this error

**Comment by benjaminmordaunt** [comment]
You're likely running a 32-bit version of Windows, where arpspoof.exe has been compiled for 64-bit Windows.

**Comment by ChocoTonic** [comment]
I am on 64 bit.

![image](https://user-images.githubusercontent.com/41702116/44951597-f9ea4f80-ae1c-11e8-8c7d-73888b4a0b4b.png)

**Comment by alandau** [comment]
The executable available through the Releases page is compiled for 32 bits. This means it needs a 32-bit version of wpcap.dll, which based on the error message, your system lacks.

I installed the 64-bit version of Wireshark on my system and it installed both the 32-bit and the 64-bit version of wpcap.dll. Please do the same and reopen this issue if it still doesn't work
